# Generated by Django 5.0.2 on 2024-02-15 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password2',
        ),
    ]
