# Generated by Django 5.0.2 on 2024-02-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customuser_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='original_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
